### PR TITLE
Theme Tweaks

### PR DESCRIPTION
**Pull request by zwbetz-gh**
Hey there. I recently used your hero theme on a side project. (Out of all the available hugo themes, they picked yours based on the design, so props). 

Made a few tweaks when implementing it, so thought I'd give back. Thanks for making this theme 👍 

Changes:
- Allow custom css files by accepting an array of `assets` dir file paths
- Allow contact page address to enter and show newlines
- Allow contact page business hours to be specified in config, not hardcoded in template

### CODE REVIEW

**Comment by zwbetz-gh** [comment]
Was looking through the open issues. Looks like this PR would partially address https://github.com/zerostaticthemes/hugo-hero-theme/issues/22

**Comment by zwbetz-gh** [comment]
Bump

**Comment by JugglerX** [comment]
@zwbetz-gh sorry for the delay mate. Thank you so much for the PR. 

I like what you've added for the contact page.

Can you explain the use case/advantage of the custom css? Isn't it just as easy to add a new @import to the style.scss?

**Comment by zwbetz-gh** [comment]
I prefer working with CSS over SCSS because I'm a bit old-school. But fair point. Someone could just edit the `style.scss`. I'll remove the custom CSS config changes from this PR.

**Comment by zwbetz-gh** [comment]
Removed in https://github.com/zerostaticthemes/hugo-hero-theme/pull/28/commits/406ec59bc9a8cd4cd03da97aa35e025c51cab79a

Now just the Contact page changes remain.

**Pull request merged**
